# Shows a version using environmental variables for configuration
# In theory should work but it didn't in our tests.
version: '3.8'
services:
  squadjs:
    image: localhost/squadjs-docker:latest
    volumes:
      - "./test.log:/logs/SquadGame.log"
    #env_file:
    #  - .env
    environment:
      - config='{"server":{"id":1,"host":"192.168.1.51","queryPort":27165,"rconPort":21114,"rconPassword":"sakura","logReaderMode":"tail","logDir":"/logs/","ftp":{"host":"xxx.xxx.xxx.xxx","port":21,"user":"FTP Username","password":"FTP Password"},"sftp":{"host":"xxx.xxx.xxx.xxx","port":22,"username":"SFTP Username","password":"SFTP Password"},"adminLists":[{"type":"","source":""}]},"connectors":{"sqlite":"sqlite:database.sqlite"},"plugins":[],"logger":{"verboseness":{"SquadServer":1,"LogParser":1,"RCON":1},"colors":{"SquadServer":"yellowBright","SquadServerFactory":"yellowBright","LogParser":"blueBright","RCON":"redBright"}}}'